### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by cryptoknightsz** [klaksik/memhash_miner#1]
```
DevTools listening on ws://127.0.0.1:50890/devtools/browser/9a3e76df-326b-4d1b-a976-cd12d9c0caee
[123364:178984:1126/171907.201:ERROR:direct_composition_support.cc(1034)] QueryInterface to IDCompositionDevice4 failed: No such interface supported (0x80004002)
Ошибка: Message: invalid argument
  (Session info: chrome=131.0.6778.70)
Stacktrace:
        GetHandleVerifier [0x005333E3+25059]
        (No symbol) [0x004BCDE4]
        (No symbol) [0x0039BD39]
        (No symbol) [0x0038CF61]
        (No symbol) [0x0038B88B]
        (No symbol) [0x0038BE6B]
        (No symbol) [0x0039E8BE]
        (No symbol) [0x0041BF47]
        (No symbol) [0x00401EFC]
        (No symbol) [0x0041B51E]
        (No symbol) [0x00401C96]
        (No symbol) [0x003D3FAC]
        (No symbol) [0x003D4F3D]
        GetHandleVerifier [0x00825543+3113795]
        GetHandleVerifier [0x0083A20A+3198986]
        GetHandleVerifier [0x008329E2+3168226]
        GetHandleVerifier [0x005D3250+680016]
        (No symbol) [0x004C572D]
        (No symbol) [0x004C29D8]
        (No symbol) [0x004C2B75]
        (No symbol) [0x004B57D0]
        BaseThreadInitThunk [0x7681FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77D5809E+286]
        RtlGetAppContainerNamedObjectPath [0x77D5806E+238]```

**Comment by klaksik** [comment]
Graphics or Composition Issue: The IDCompositionDevice4 error often relates to DirectComposition. Try launching Chrome with the --disable-gpu flag. And try install Chrome on your linux server

**Comment by XNFTHUNETRZ** [comment]
I'm using windows with portable telegram on it

**Comment by klaksik** [comment]
This script development for Linux, if you need using with windows wait some days while i'm develop this, also don't forget paste url to main.py

**Comment by XNFTHUNETRZ** [comment]
Ok, I'll be waiting 
Also, what url?

**Comment by klaksik** [comment]
Oh sorry, I had to add this to guide, wait 30 minutes, I'm update guide

**Comment by XNFTHUNETRZ** [comment]
Sure, and wen for windows ser?

**Comment by klaksik** [comment]
i`m wroat guide, go to main repo page

**Comment by XNFTHUNETRZ** [comment]
That's good, but I need for windows

**Comment by XNFTHUNETRZ** [comment]
Wen for windows ser

**Comment by klaksik** [comment]
ready

**Comment by klaksik** [comment]
no ser, this script full legal. reasons for ban: 1) майнить на серверах можно 
2) майнить на gpu нельзя
3) нельзя майнить с одного акаунта на разных устройствах ОДНОВРЕМЕННО 
4) на одном устройстве можно с 1-3 трех акаунтов майнить максимум за все время майнинга. 
5) самое главное- майнить можно на чем угодно - нельзя модифицировать скрипты майнинга.
1) it is possible to mine on servers 
2) you cannot mine on gpu
3) you can not mine from one account on different devices at the same time. 
4) on one device you can mine from 1-3 three accounts maximum for the whole time of mining. 
5) the most important thing is that you can mine on anything - you cannot modify the mining scripts.


it is offical comment
