### ISSUE TITLE
cant run 

### ISSUE THREAD

**Issue by gamang** [klaksik/memhash_miner#2]
sir , icant run because invalid token

**Comment by cryptoknightsz** [comment]
Check your token then

**Comment by klaksik** [comment]
don`t forget clause 5 and 6

**Comment by gamang** [comment]
i dont know how to do that , can you make tutorial vidio

**Comment by gamang** [comment]
can u just put using querry or token bearer ?

**Comment by klaksik** [comment]
fixed, check readme
