### ISSUE TITLE
Doesnt work anymore!

### ISSUE THREAD

**Issue by 7urkm3n** [klaksik/memhash_miner#4]
Seems like it was updated last couple days, It uses canvas over iframe now. 

Need to  figure out different way

**Comment by klaksik** [comment]
I'm thinking of fixing it, those who copied the link can use it.

**Comment by klaksik** [comment]
fixed

**Comment by Axadiw** [comment]
Last commit in this repo is 2 weeks old, are you sure that you've pushed the fix?:)

**Comment by 7urkm3n** [comment]
> Last commit in this repo is 2 weeks old, are you sure that you've pushed the fix?:)

Yes its fixed now. Telegram updated or reverted back to iframe again. 

If you inspect through telegram app, its CANVAS, but web mini apps use IFRAME. 

I hope, telegram will keep this update :)
